name: pysnowpark
channels:
  - https://repo.anaconda.com/pkgs/snowflake
  - nodefaults
dependencies:
  - python=3.8.15
  - snowflake-snowpark-python
  - pip
  - pip:
    - pyopenssl==22.1.0
    - snowflake-cli-labs
    - streamlit
    - matplotlib
    - seaborn
